apiVersion: v1
kind: Service
metadata:
  name: buildit-jenkins
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildit-jenkins-config
data:
  JENKINS_CONFIG_FILE: https://github.com/buildit/jenkins-config.git
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: buildit-jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: builditdigital/jenkins-image:1.0.9-alpine
        name: jenkins
        env:
        - name: JENKINS_CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: buildit-jenkins-config
              key: JENKINS_CONFIG_FILE
        # Secret created manually: https://kubernetes.io/docs/concepts/configuration/secret/#creating-your-own-secrets
        - name: JENKINS_STARTUP_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-startup-secret
              key: JENKINS_STARTUP_SECRET
        ports:
        - containerPort: 8080
          name: http
---
# Follow this to install nginx ingress controller: https://github.com/kubernetes/ingress-nginx/tree/master/deploy
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    # Chooses a random port on the node by default (30000-32767). Describe the service to get the chosen port.
    # Uncomment to set explicitly - it must be in the above range.
    #nodePort: 30000
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    # Chooses a random port on the node by default (30000-32767). Describe the service to get the chosen port.
    # Uncomment to set explicitly - it must be in the above range. 
    #nodePort: 30443
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buildit-jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # Your DNS has to be able to resolve this hostname
  - host: buildit-jenkins.portworx.zone
    http:
      paths:
      - backend: 
          serviceName: buildit-jenkins
          servicePort: 80
